# Generated by Django 2.1.2 on 2018-10-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='closed',
            field=models.BooleanField(null=True, verbose_name='Closed'),
        ),
        migrations.AddField(
            model_name='board',
            name='last_activity',
            field=models.DateTimeField(null=True, verbose_name='Last activity'),
        ),
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Board'),
        ),
        migrations.AddField(
            model_name='card',
            name='boardlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.BoardList'),
        ),
        migrations.AddField(
            model_name='member',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Card'),
        ),
    ]
