# Generated by Django 2.1.2 on 2018-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0003_auto_20181031_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_activity',
            field=models.DateTimeField(null=True, verbose_name='Last activity'),
        ),
    ]
