# Generated by Django 2.1.2 on 2018-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0004_card_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='card',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(to='trelloapps.Member'),
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(to='trelloapps.Member'),
        ),
    ]
