# Generated by Django 2.1.2 on 2018-10-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0005_auto_20181031_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='childs',
            field=models.ManyToManyField(to='trelloapps.Card'),
        ),
    ]
