# Generated by Django 2.1.2 on 2018-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0007_auto_20181031_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
    ]
