# Generated by Django 2.1.2 on 2018-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0008_auto_20181031_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
