# Generated by Django 2.1.2 on 2018-10-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0009_auto_20181031_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Board')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='memberboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Board'),
        ),
    ]
