# Generated by Django 2.1.2 on 2018-11-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0010_auto_20181031_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='childs',
        ),
        migrations.AddField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Card'),
        ),
    ]
