# Generated by Django 2.1.2 on 2018-11-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0013_auto_20181101_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='position',
        ),
        migrations.AddField(
            model_name='boardlist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.BoardList'),
        ),
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Card'),
        ),
    ]
