# Generated by Django 2.1.2 on 2018-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0014_auto_20181101_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='position',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
    ]
