# Generated by Django 2.1.2 on 2018-11-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0015_auto_20181101_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='member',
            name='memberboard',
        ),
        migrations.RemoveField(
            model_name='project',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Member'),
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Project'),
        ),
    ]
