# Generated by Django 2.1.3 on 2018-11-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0016_auto_20181101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Member', unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trelloapps.Project', unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='remoteid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='boardlist',
            name='remoteid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='remoteid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='remoteid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='remoteid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='boardlist',
            unique_together={('board', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('board', 'name')},
        ),
    ]
