# Generated by Django 2.1.3 on 2018-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0017_auto_20181102_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last activity'),
        ),
    ]
