# Generated by Django 2.1.3 on 2018-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0019_auto_20181105_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='trelloapps.Label'),
        ),
    ]
