# Generated by Django 2.1.3 on 2018-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0020_card_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='marker_to_update',
            field=models.BooleanField(default=False, verbose_name='Marked to update'),
        ),
    ]
