# Generated by Django 2.1.3 on 2018-11-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0022_auto_20181105_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='marker_to_delete',
        ),
        migrations.AddField(
            model_name='card',
            name='delete_remotely',
            field=models.BooleanField(default=False, verbose_name='Marked to delete remotely'),
        ),
        migrations.AddField(
            model_name='card',
            name='update_info',
            field=models.BooleanField(default=False, verbose_name='Update info'),
        ),
        migrations.AddField(
            model_name='card',
            name='update_labels',
            field=models.BooleanField(default=False, verbose_name='Update labels'),
        ),
        migrations.AddField(
            model_name='card',
            name='update_members',
            field=models.BooleanField(default=False, verbose_name='Update members'),
        ),
    ]
