# Generated by Django 2.1.3 on 2018-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0023_auto_20181105_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='update_list',
            field=models.BooleanField(default=False, verbose_name='Update list'),
        ),
    ]
