# Generated by Django 2.1.3 on 2018-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapps', '0024_card_update_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='update_info',
        ),
        migrations.AddField(
            model_name='card',
            name='update_closed',
            field=models.BooleanField(default=False, verbose_name='Update closed'),
        ),
        migrations.AddField(
            model_name='card',
            name='update_desc',
            field=models.BooleanField(default=False, verbose_name='Update desc'),
        ),
        migrations.AddField(
            model_name='card',
            name='update_name',
            field=models.BooleanField(default=False, verbose_name='Update name'),
        ),
    ]
